Домашнее задание «Библиотека numpy. Вычислительные задачи»

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np
N = 12
x.reshape(N)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [42]:
import numpy as np
np.diag(np.arange(0, 28, 4), k = 0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0, 20,  0],
       [ 0,  0,  0,  0,  0,  0, 24]])

In [51]:
z = np.diag(np.arange(0, 28, 4), k = 0)
print(sum(([sum(row) for row in z])))


84


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [65]:
4*0.46666667+2*3.84444444-5.55555556

4.0

In [66]:
 0.46666667+3*3.84444444

11.999999990000001

In [67]:
5*3.84444444+4*(-5.55555556)

-3.0000000399999998

In [63]:
import numpy as np
from numpy import linalg
a = np.array([[4,2,1], [1,3,0], [0,5,4]])
b = np.array([4,12,-3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [64]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array

In [55]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее: 
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [56]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


In [57]:
def cosine(users_stats, next_user_stats):
    """
    Подсчет косинуса угла между векторами user_stats ,next_user_stats по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm(users_stats)
    bLength = np.linalg.norm(next_user_stats)
    
    return np.dot(users_stats, next_user_stats) / (aLength * bLength)

In [58]:
cosine(users_stats, next_user_stats)

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

In [60]:
np.arccos(cosine(users_stats, next_user_stats)) * 360 / 2 / np.pi

array([87.31294754, 76.44352944, 84.61996229, 76.44352944, 84.61996229,
       90.        , 90.        , 81.91499249, 90.        , 90.        ])